spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  bootstrapApplications:
    - name: traefik
      repoURL: 'https://helm.traefik.io/traefik'
      targetRevision: '26.0.0'
      chart: traefik
      namespace: traefik
      helm:
        parameters:
          # Tells Traefik to populate the ADDRESS field on all Ingresses
          - name: "providers.kubernetesIngress.publishedService.enabled"
            value: "true"
    - name: cert-manager
      repoURL: 'https://charts.jetstack.io/'
      targetRevision: 'v1.20.1'
      chart: cert-manager
      namespace: cert-manager
      helm:
        parameters:
          - name: "crds.enabled"
            value: "true"